export default {

	TOGGLE_LOADING: 'TOGGLE_LOADING',

	SELECT_MENU_ITEM: 'SELECT_MENU_ITEM',

	COURSES_RECEIVED: 'COURSES_RECEIVED',

	TUTORIALS_RECEIVED: 'TUTORIALS_RECEIVED',
	TUTORIAL_UPDATED: 'TUTORIAL_UPDATED',
	
	CURRENT_USER_RECIEVED: 'CURRENT_USER_RECIEVED'
	
}